language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install pytest
  - pip install pylint
  - pip install -r requirements.txt
  - cd pertbio; python setup.py install
  
script:
  - python -m pytest test.py
  - cd pertbio; pylint --disable=line-too-long,invalid-name,too-many-arguments,too-many-locals,too-few-public-methods,broad-except,too-many-instance-attributes,too-many-function-args pertbio
  
