language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install pylint
  - pip install -r requirements.txt
  - cd pertbio; python setup.py install
  
script:
  - cd ..; python scripts/main.py -config=configs/example.cfg.json
  - cd pertbio; pylint --disable=--disable=line-too-long,invalid-name,too-many-arguments,too-many-locals,too-few-public-methods,broad-except,too-many-instance-attributes,too-many-function-args pertbio
