language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - cd pertbio; python setup.py install
  
script:
  - cd ..
  - pylint pertbio
  - python scripts/main.py -config=configs/example.cfg.json
