language: python

python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install pylint
  - pip install -r requirements.txt
  - cd pertbio; python setup.py install
  
script:
  - cd ..; python scripts/main.py -config=configs/example.cfg.json
  - pylint pertbio
